### ISSUE TITLE
FireFox bug

### ISSUE THREAD

**Issue by k0t0vich** [KTXSoftware/BlocksFromHeaven#2]
When starting examlpe 
https://dl.dropboxusercontent.com/u/24767857/any/html5/index.xhtml
in firefox
https://scontent-amt2-1.xx.fbcdn.net/v/t1.0-9/13627238_1184772498254269_4656162182920366209_n.jpg?oh=a311829d153b6453da08187c31b03c6d&oe=5829919C

**Comment by RobDangerous** [comment]
Firefox just times out, you can click on continue and it works.
That's because the sample decodes all the music in advance. Will eventually change that but it's not a bug per se and browsers just react that way when you do long calculations on the main thread.
